id: Ledger
namespace: dev
labels:
  Type: Source
  Group: Ledger
  Owner: Finance

triggers:
  - id: daily_3am
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 3 * * *"

inputs:
  - id: start_date_manual
    displayName: Start Date 
    type: DATE
    required: true
  - id: end_date_manual
    displayName: End Date
    type: DATE
    required: true

variables:
  n: 20000
  dataset: mp_infor

tasks:
  - id: calculate_dates
    type: io.kestra.plugin.core.debug.Return
    format: |
      {
        "start_date": "{% if inputs.start_date_manual is defined and inputs.start_date_manual is not null %}{{ inputs.start_date_manual | date('yyyy-MM-dd') }}{% else %}{{ trigger.date | dateAdd(-5, 'DAYS') | date('yyyy-MM-dd') }}{% endif %}",
        "end_date": "{% if inputs.end_date_manual is defined and inputs.end_date_manual is not null %}{{ inputs.end_date_manual | date('yyyy-MM-dd') }}{% else %}{{ trigger.date | date('yyyy-MM-dd') }}{% endif %}"
      }

  - id: ledger_parallel
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: run_el_ledger_notes
        type: io.kestra.plugin.core.flow.Subflow
        flowId: generic_extract_load_infor_append
        namespace: dev
        
        inputs:
          append_strategy: DAILY
          api_path_and_query: https://csi10a.erpsl.se2.inforcloudsuite.com/IDORequestService/ido/load/ue_ID_MP_SLObjectNotes?properties=DerDesc,DerContent,RecordDate,ue_SpcnRecordDate,RefRowPointer,RowPointer&filter=NoteHeaderToken=4 AND RecordDate >= '{{ json(outputs.calculate_dates.value).start_date }}' AND RecordDate <= '{{ json(outputs.calculate_dates.value).end_date }}'&recordCap={{ vars.n }}&loadType=NEXT

          start_date: "{{ json(outputs.calculate_dates.value).start_date }}"
          end_date: "{{ json(outputs.calculate_dates.value).end_date }}"
          bq_destination_table: "{{ vars.dataset }}.ledger_notes"
          date_field: "RecordDate"
          bq_schema_fields: |
            {
              'RecordDate' : 'date',
              'ue_SpcnRecordDate' : 'date'
            }
            
      - id: run_el_ledger
        type: io.kestra.plugin.core.flow.Subflow
        flowId: generic_extract_load_infor_append
        namespace: dev
        
        inputs:
          append_strategy: DAILY
          api_path_and_query: https://csi10a.erpsl.se2.inforcloudsuite.com/IDORequestService/ido/load/SLLedgers?properties=Acct,AcctUnit1,AcctUnit2,AcctUnit3,AcctUnit4,BankCode,ChaDescription,CheckDate,CheckNum,Consolidated,ControlNumber,ControlPeriod,ControlPrefix,ControlSite,ControlYear,CurrAmtFormat,CurrCode,CurrCstPrcFormat,DerApproveDate,DerApprover,DerCustVendName,DerDomAmountCredit,DerDomAmountDebit,DerForAmountCredit,DerForAmountDebit,DerSumDomAmount,DerVoucher,DerVoucher1,DocumentNum,DomAmount,DTransNum,ExchRate,ForAmount,FRDerDate,FRDerDescription,FRDerInvDate,FRDerSign,FromId,FromSite,Hierarchy,JournalBatchId,MatlTransNum,Processed,Ref,RefControlNumber,RefControlPeriod,RefControlPrefix,RefControlSite,RefControlYear,RefType,Site,THPaymentNumber,TransDate,TransNum,UbCHGLVouNum,UbCHLineNum,UbCHRubric,VendNum,VendNumSource,Voucher,VouchSeq,JhType,Type,ProjTransNum,Cancellation,GLVoucher,FRLetter,FRLetteringDate,EnableCancellationPosting,RecordDate,RowPointer&filter=TransDate >= '{{ json(outputs.calculate_dates.value).start_date }}' AND TransDate <= '{{ json(outputs.calculate_dates.value).end_date }}'&recordCap={{ vars.n }}&loadType=NEXT
          start_date: "{{ json(outputs.calculate_dates.value).start_date }}"
          end_date: "{{ json(outputs.calculate_dates.value).end_date }}"
          bq_destination_table: "{{ vars.dataset }}.ledger"
          date_field: "TransDate"
          bq_schema_fields: |
            {
              'CheckDate' : 'date',
              'CheckNum' : 'int',
              'ControlNumber' : 'int',
              'ControlYear' : 'int',
              'DerApproveDate' : 'date',
              'DerDomAmountCredit' : 'float',
              'DerDomAmountDebit' : 'float',
              'DerForAmountCredit' : 'float',
              'DerForAmountDebit' : 'float',
              'DerSumDomAmount' : 'float',
              'DomAmount' : 'float',
              'DTransNum' : 'int',
              'ExchRate' : 'float',
              'ForAmount' : 'float',
              'FRDerDate' : 'date',
              'FRDerInvDate' : 'date',
              'JournalBatchId' : 'float',
              'MatlTransNum' : 'int',
              'RecordDate' : 'date',
              'RefControlNumber' : 'int',
              'RefControlYear' : 'int',
              'TransDate' : 'date',
              'TransNum' : 'int',
              'UbCHLineNum' : 'int',
              'VouchSeq' : 'int',
              'ProjTransNum' : 'int',
              'FRLetteringDate' : 'date'
            }
