id: MP45_SaldoAwalQty_MP
namespace: dev
labels:
  Type: Source
  Group: Inventory Movement

triggers:
  - id: daily_3am
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 3 * * *"

inputs:
  - id: start_date_manual
    type: DATE
    required: true
    displayName: Start Date
  - id: end_date_manual
    type: DATE
    required: true
    displayName: End Date
  - id: site
    type: SELECT
    required: false
    displayName: Site
    values:
      - KBPR
      - MP
      - KTWL
      - FGJM
    defaults: MP
    
variables:
  n: 20000
  dataset: mp_infor

tasks:
  - id: MovementValueParalel
    type: io.kestra.plugin.core.flow.Parallel
    tasks:

#-------------------------------------------------------------------------- saldo_awal_qty_mp_bq --------------------------------------------------------------------------#

      - id: run_el_saldo_awal_qty_mp_bq
        type: io.kestra.plugin.core.flow.Subflow
        flowId: generic_extract_load_infor_append
        namespace: dev
        
        inputs:
          append_strategy: MONTHLY_SITE
          api_path_and_query: https://csi10a.erpsl.se2.inforcloudsuite.com/IDORequestService/ido/load/ue_ID_MP45_InventoryMoveQty?properties=ue_Item,ue_ItemDesc,ue_ProdDesc,ue_ProductCode,ue_Customer,ue_CustName,ue_ConvFactor,ue_UM,ue_QtyBeginning,ue_QtyBeginning_Pcs&clm=SP_MP45_StockMoveQty&clmparam={{ inputs.start_date_manual }},{{ inputs.end_date_manual }},,,,,1
          
          start_date: "{{ inputs.start_date_manual }}"
          end_date: "{{ inputs.end_date_manual }}"
          bq_destination_table: "{{ vars.dataset }}.saldo_awal_qty_mp_bq"
          date_field: "month_year"
          site: "{{ inputs.site }}"
          site_field: site
          bq_schema_fields: |
            {
              'ue_ConvFactor' : 'float',
              'ue_QtyBeginning' : 'float',
              'ue_QtyBeginning_Pcs' : 'float'
            }

#-------------------------------------------------------------------------- Movement_qty_mp_v --------------------------------------------------------------------------#

  - id: ViewMovement_qty_mp_v
    type: io.kestra.plugin.core.flow.Subflow
    flowId: generic_transform_dbt_build
    namespace: dev

    inputs: 
      dbt_models: DataInfor.movement_qty_mp_v
      environment: prod